package com.vishal.aiyoutube.ai_analysis_service.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.List;
import java.util.UUID;

/**
 * Data Transfer Object representing the final synthesized research report.
 * This event is the terminal output of the AI Analysis Service, published
 * to Kafka for the Topic Management Service to persist and display to the user.
 */
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class AnalysisCompletedEvent {

    /**
     * Unique identifier linking the analysis back to the original user query.
     */
    private UUID topicId;

    /**
     * The high-level executive summary generated by the AI agents.
     * Provides a consolidated view of the research topic (e.g., Budget 2026).
     */
    private String finalSummary;

    /**
     * Quantitative metric (0.0 to 1.0) representing the overall tone
     * of the gathered video data.
     */
    private Double sentimentScore;

    /**
     * Quantitative metric representing how much the different video
     * sources agree on the key points.
     */
    private Double consensusPercentage;

    /**
     * A structured list of recurring claims or facts identified across
     * multiple transcripts.
     */
    private String commonClaims;

    /**
     * List of timestamped evidence from the source videos.
     * This powers the 'Source Intelligence' cards on the Nexus AI dashboard.
     */
    private List<VideoSegmentDTO> segments;

    /**
     * Inner static class representing specific evidence extracted from a single video.
     */
    @Data
    @Builder
    @AllArgsConstructor
    @NoArgsConstructor
    public static class VideoSegmentDTO {

        /**
         * YouTube unique identifier for the source video.
         */
        private String videoId;

        /**
         * The title of the source video for UI display.
         */
        private String videoTitle;

        /**
         * Direct link to the source video for user redirection.
         */
        private String videoUrl;

        /**
         * The specific moment in the video (e.g., "02:15") where the
         * insight was extracted.
         */
        private String timestamp;

        /**
         * The AI's reasoning for why this specific segment is valuable.
         */
        private String bestExplanation;

        /**
         * A brief summary of what was spoken during this segment.
         */
        private String segmentSummary;
    }
}